### ISSUE TITLE
mark broken is broken

### ISSUE THREAD

**Issue by beckermr** [conda-forge/cf-mark-broken#64]
The action on master is not currently copying packages between labels correctly

**Comment by beckermr** [comment]
It appears that the copy command doesn't like to copy packages from the same user to the same user.

**Comment by isuruf** [comment]
Maybe use `anaconda label --copy` ?

**Comment by beckermr** [comment]
that is all objects, we can use the api end point directly

I cannot push the change right now, but I will try to push tonight
